#!/usr/bin/env python3
"""Generate dependency/build helper scripts from a pinned KiCad source tree."""

from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import stat
import subprocess
from pathlib import Path
from typing import Iterable


HEADER = """# Generated by scripts/convert-kicad-deps.py.
# Source KiCad version: {version}
# Source KiCad commit: {commit}
# Do not edit by hand; rerun scripts/update-kicad-deps.sh.
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--kicad-source", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument("--target-version", required=True)
    parser.add_argument("--target-major", required=True)
    parser.add_argument("--commit", required=True)
    args = parser.parse_args()

    source = args.kicad_source.resolve()
    if not (source / "CMakeLists.txt").is_file():
        raise SystemExit(f"KiCad source directory is not valid: {source}")

    actual_commit = git_commit(source) or args.commit
    if actual_commit != args.commit:
        raise SystemExit(
            "KiCad source commit mismatch:\n"
            f"  expected: {args.commit}\n"
            f"  actual:   {actual_commit}\n"
            f"  source:   {source}"
        )

    output = args.output_dir.resolve()
    output.mkdir(parents=True, exist_ok=True)

    apt_packages = parse_apt_packages(source / "install-deps.sh")
    vcpkg_manifest = json.loads((source / "vcpkg.json").read_text(encoding="utf-8"))

    write_executable(
        output / "install-linux-apt.sh",
        render_linux_apt(args.target_version, actual_commit, apt_packages),
    )
    write_executable(
        output / "install-windows-vcpkg.ps1",
        render_windows_vcpkg(args.target_version, actual_commit, vcpkg_manifest),
    )
    write_executable(
        output / "ci-ubuntu20.04-build.sh",
        render_ci_shell(
            args.target_version,
            actual_commit,
            ".gitlab/Ubuntu-20.04-CI.yml",
            extract_gitlab_script(source / ".gitlab/Ubuntu-20.04-CI.yml", ".ubuntu20.04_build"),
        ),
    )
    write_executable(
        output / "ci-fedora-build.sh",
        render_ci_shell(
            args.target_version,
            actual_commit,
            ".gitlab/Fedora-Linux-CI.yml",
            extract_gitlab_script(source / ".gitlab/Fedora-Linux-CI.yml", ".fedora_build_linux_base"),
        ),
    )
    write_executable(
        output / "ci-macos-build.sh",
        render_ci_shell(
            args.target_version,
            actual_commit,
            ".gitlab/macOS-CI.yml",
            extract_gitlab_script(source / ".gitlab/macOS-CI.yml", "macos_build"),
        ),
    )

    write_readme(output / "README.md", args.target_version, actual_commit)
    return 0


def git_commit(source: Path) -> str | None:
    try:
        return subprocess.check_output(
            ["git", "-C", str(source), "rev-parse", "HEAD"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        return None


def parse_apt_packages(path: Path) -> list[str]:
    packages: list[str] = []
    in_install = False

    for line in path.read_text(encoding="utf-8").splitlines():
        body = line.split("#", 1)[0].strip()
        if not body:
            continue

        if "apt-get install" in body:
            in_install = True
            body = body.split("apt-get install", 1)[1]
        elif not in_install:
            continue

        body = body.replace("\\", " ").strip()
        for token in shlex.split(body):
            if token in {"sudo", "apt-get", "update", "install", "&&"}:
                continue
            if token.startswith("-"):
                continue
            packages.append(token)

        if in_install and not line.rstrip().endswith("\\"):
            break

    return dedupe(packages)


def extract_gitlab_script(path: Path, job: str) -> list[str]:
    lines = path.read_text(encoding="utf-8").splitlines()
    job_re = re.compile(rf"^{re.escape(job)}:\s*$")
    start = next((index for index, line in enumerate(lines) if job_re.match(line)), None)
    if start is None:
        raise SystemExit(f"Job {job!r} not found in {path}")

    end = len(lines)
    for index in range(start + 1, len(lines)):
        line = lines[index]
        if line and not line.startswith((" ", "\t")) and not line.lstrip().startswith("#"):
            end = index
            break

    script_start = None
    for index in range(start + 1, end):
        if lines[index].strip() == "script:":
            script_start = index + 1
            break
    if script_start is None:
        raise SystemExit(f"Job {job!r} has no script section in {path}")

    commands: list[str] = []
    current: list[str] = []

    for line in lines[script_start:end]:
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("#"):
            continue
        indent = len(line) - len(line.lstrip(" "))
        if indent <= 2:
            break
        if indent == 4 and stripped.startswith("- "):
            if current:
                commands.append(" ".join(current))
            current = [stripped[2:].strip()]
            continue
        if current and indent > 4:
            current.append(stripped)
            continue
        if current:
            commands.append(" ".join(current))
            current = []

    if current:
        commands.append(" ".join(current))

    return commands


def render_linux_apt(version: str, commit: str, packages: Iterable[str]) -> str:
    package_lines = " \\\n  ".join(packages)
    return (
        "#!/usr/bin/env sh\n"
        "set -eu\n\n"
        + HEADER.format(version=version, commit=commit)
        + "\n"
        "if [ \"${SUDO+x}\" != x ]; then\n"
        "    if [ \"$(id -u)\" = \"0\" ]; then\n"
        "        SUDO=\"\"\n"
        "    else\n"
        "        SUDO=\"sudo\"\n"
        "    fi\n"
        "fi\n\n"
        "# shellcheck disable=SC2086\n"
        "$SUDO apt-get update\n"
        "# shellcheck disable=SC2086\n"
        "$SUDO apt-get install -y \\\n"
        f"  {package_lines}\n"
    )


def render_windows_vcpkg(version: str, commit: str, manifest: dict) -> str:
    manifest_text = json.dumps(manifest, indent=2, sort_keys=False)
    return (
        "param(\n"
        "    [string]$VcpkgRoot = $env:VCPKG_ROOT,\n"
        "    [string]$Triplet = $(if ($env:VCPKG_DEFAULT_TRIPLET) { $env:VCPKG_DEFAULT_TRIPLET } else { 'x64-windows' }),\n"
        "    [string]$InstallRoot = $(Join-Path $PSScriptRoot 'vcpkg_installed')\n"
        ")\n\n"
        "$ErrorActionPreference = 'Stop'\n\n"
        + HEADER.format(version=version, commit=commit).replace("#", "#")
        + "\n"
        "if (-not $VcpkgRoot) {\n"
        "    $VcpkgRoot = 'C:\\builder\\vcpkg'\n"
        "}\n\n"
        "$vcpkgExe = Join-Path $VcpkgRoot 'vcpkg.exe'\n"
        "if (-not (Test-Path $vcpkgExe)) {\n"
        "    throw \"vcpkg.exe not found. Set VCPKG_ROOT or pass -VcpkgRoot.\"\n"
        "}\n\n"
        "$manifestRoot = Join-Path $PSScriptRoot '.vcpkg-manifest'\n"
        "New-Item -ItemType Directory -Force -Path $manifestRoot | Out-Null\n"
        "@'\n"
        f"{manifest_text}\n"
        "'@ | Set-Content -Encoding utf8 -Path (Join-Path $manifestRoot 'vcpkg.json')\n\n"
        "& $vcpkgExe install `\n"
        "    --x-manifest-root=$manifestRoot `\n"
        "    --triplet=$Triplet `\n"
        "    --x-install-root=$InstallRoot `\n"
        "    --x-abi-tools-use-exact-versions\n"
    )


def render_ci_shell(version: str, commit: str, source_label: str, commands: Iterable[str]) -> str:
    body = "\n".join(commands)
    return (
        "#!/usr/bin/env sh\n"
        "set -eu\n\n"
        + HEADER.format(version=version, commit=commit)
        + f"# Converted from KiCad {source_label}.\n\n"
        "KICAD_SOURCE_DIR=\"${KICAD_SOURCE_DIR:-}\"\n"
        "if [ -z \"$KICAD_SOURCE_DIR\" ]; then\n"
        "    echo \"Set KICAD_SOURCE_DIR to the pinned KiCad source checkout.\" >&2\n"
        "    exit 2\n"
        "fi\n\n"
        "cd \"$KICAD_SOURCE_DIR\"\n"
        f"{body}\n"
    )


def write_readme(path: Path, version: str, commit: str) -> None:
    path.write_text(
        f"""# Generated KiCad Dependency Scripts

Generated by `scripts/convert-kicad-deps.py` from KiCad {version}.

Pinned source commit: `{commit}`

Run `scripts/update-kicad-deps.sh` after changing the target KiCad version,
tag, or commit. The generated scripts are committed so dependency setup can be
reviewed and reproduced without copying package names out of prose docs.
""",
        encoding="utf-8",
    )


def dedupe(values: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        result.append(value)
    return result


def write_executable(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")
    current = path.stat().st_mode
    path.chmod(current | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


if __name__ == "__main__":
    raise SystemExit(main())
